# Generated by Django 4.0.6 on 2022-07-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='program_abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
