# Generated by Django 4.0.6 on 2022-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_university_program_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='last_merit',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='university',
            name='program_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
