# Generated by Django 4.0.6 on 2022-07-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_university_last_merit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='program_abbreviation',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
