# Generated by Django 4.0.6 on 2022-07-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_saveditems_item_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedItems',
        ),
    ]
