# Generated by Django 4.0.6 on 2022-07-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_saveditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversitiesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
